# Netlify deployment configuration
[build]
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (you'll set these in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"